
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Sat May 30 12:32:52 BRT 2015
//----------------------------------------------------

package parser;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int OUTPUT_IDENTIFIER = 15;
  public static final int INPUT_IDENTIFIER = 14;
  public static final int R_PAR = 5;
  public static final int R_BRACE = 7;
  public static final int PLUS = 11;
  public static final int EOF = 0;
  public static final int INORDER = 2;
  public static final int APOSTROPHE = 10;
  public static final int OUTORDER = 3;
  public static final int ASSIGN = 13;
  public static final int error = 1;
  public static final int EXCLAMATION = 9;
  public static final int SEMICOLON = 8;
  public static final int TIMES = 12;
  public static final int L_PAR = 4;
  public static final int L_BRACE = 6;
}

